// Generated by CoffeeScript 1.7.1
(function() {
  var Settings;

  Settings = (function() {
    function Settings() {}

    Settings.prototype.show = function() {};

    return Settings;

  })();

  $(function() {
    if (window.goule == null) {
      window.goule = {};
    }
    return window.goule.settings = new Settings();
  });

}).call(this);
