// Generated by CoffeeScript 1.7.1
(function() {
  var ServiceList;

  ServiceList = (function() {
    function ServiceList() {}

    ServiceList.prototype.show = function() {};

    return ServiceList;

  })();

  $(function() {
    if (window.goule == null) {
      window.goule = {};
    }
    return window.goule.list = new ServiceList();
  });

}).call(this);
