// Generated by CoffeeScript 1.7.1
(function() {
  var Tabs;

  Tabs = (function() {
    function Tabs() {
      this.element = $('#active-tab-indicator');
      this.showing = '';
    }

    Tabs.prototype.change = function(button, animate) {
      var attributes;
      if (animate == null) {
        animate = true;
      }
      this.showing = button[0].id;
      if (animate) {
        attributes = {
          'width': button.outerWidth(),
          'left': button.offset().left
        };
        return this.element.animate(attributes, 'fast', function() {});
      } else {
        return this.element.css({
          'width': button.outerWidth() + 'px',
          'left': button.offset().left + 'px'
        });
      }
    };

    Tabs.prototype._setupButton = function(name, showFunc) {
      var tab;
      tab = $('#' + name);
      return tab.click((function(_this) {
        return function() {
          if (_this.showing === name) {
            return;
          }
          showFunc();
          return _this.change(tab);
        };
      })(this));
    };

    return Tabs;

  })();

  $(function() {
    var tabs;
    if (window.goule == null) {
      window.goule = {};
    }
    tabs = new Tabs();
    window.goule.tabs = tabs;
    tabs.change($('#list-tab'), false);
    tabs._setupButton('list-tab', function() {
      return window.goule.list.show;
    });
    return tabs._setupButton('settings-tab', function() {
      return window.goule.settings.show;
    });
  });

}).call(this);
